import { useState } from "react";
import { AppLayout } from "@/components/layout/AppLayout";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Sparkles,
  Wand2,
  FileText,
  Save,
  RefreshCw,
  ChevronRight,
  Edit2,
  Trash2,
  Upload,
  Loader2,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { useToast } from "@/hooks/use-toast";
import { Checkbox } from "@/components/ui/checkbox";
import { useProjects } from "@/hooks/useProjects";
import { useTestCases } from "@/hooks/useTestCases";
import { supabase } from "@/integrations/supabase/client";

interface GeneratedTestCase {
  id: string;
  name: string;
  description: string;
  priority: string;
  type: string;
  steps: { action: string; expected: string }[];
  selected: boolean;
}

export default function AIGeneration() {
  const [input, setInput] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [generatedTests, setGeneratedTests] = useState<GeneratedTestCase[]>([]);
  const [inputType, setInputType] = useState("description");
  const [defaultPriority, setDefaultPriority] = useState("medium");
  const [testType, setTestType] = useState("functional");
  const [selectedProjectId, setSelectedProjectId] = useState("");
  const { toast } = useToast();
  const { data: projects } = useProjects();
  const { bulkCreateTestCases } = useTestCases(selectedProjectId);

  const handleGenerate = async () => {
    if (!input.trim()) {
      toast({
        title: "Input required",
        description: "Please enter a feature description or user story.",
        variant: "destructive",
      });
      return;
    }

    setIsGenerating(true);
    setGeneratedTests([]);

    try {
      const { data, error } = await supabase.functions.invoke("generate-test-cases", {
        body: { description: input, inputType, priority: defaultPriority, testType },
      });

      if (error) throw new Error(error.message || "Failed to generate test cases");
      if (data?.error) throw new Error(data.error);
      if (!data?.test_cases?.length) throw new Error("No test cases were generated");

      const tests: GeneratedTestCase[] = data.test_cases.map((tc: any, i: number) => ({
        id: `gen-${i + 1}`,
        name: tc.name,
        description: tc.description,
        priority: tc.priority || defaultPriority,
        type: tc.type || testType,
        steps: tc.steps || [],
        selected: true,
      }));

      setGeneratedTests(tests);
      toast({
        title: "Test cases generated",
        description: `${tests.length} test cases have been generated by AI.`,
      });
    } catch (err: any) {
      console.error("AI generation failed:", err);
      toast({
        title: "Generation failed",
        description: err.message || "An error occurred while generating test cases.",
        variant: "destructive",
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const toggleTestSelection = (id: string) => {
    setGeneratedTests((prev) =>
      prev.map((test) =>
        test.id === id ? { ...test, selected: !test.selected } : test
      )
    );
  };

  const removeTest = (id: string) => {
    setGeneratedTests((prev) => prev.filter((t) => t.id !== id));
  };

  const handleSaveSelected = async () => {
    const selected = generatedTests.filter((t) => t.selected);
    if (selected.length === 0) {
      toast({
        title: "No tests selected",
        description: "Please select at least one test case to save.",
        variant: "destructive",
      });
      return;
    }

    if (!selectedProjectId) {
      toast({
        title: "No project selected",
        description: "Please select a project to save the test cases to.",
        variant: "destructive",
      });
      return;
    }

    setIsSaving(true);
    try {
      const inputs = selected.map((t) => ({
        title: t.name,
        description: t.description,
        priority: t.priority,
        test_type: t.type,
        steps: t.steps,
        project_id: selectedProjectId,
        status: "draft",
      }));

      await bulkCreateTestCases.mutateAsync(inputs);
      setGeneratedTests([]);
      setInput("");
    } catch (err: any) {
      toast({
        title: "Save failed",
        description: err.message || "Failed to save test cases.",
        variant: "destructive",
      });
    } finally {
      setIsSaving(false);
    }
  };

  const priorityColors: Record<string, string> = {
    critical: "bg-destructive text-destructive-foreground",
    high: "bg-chart-4 text-foreground",
    medium: "bg-chart-1 text-foreground",
    low: "bg-muted text-muted-foreground",
  };

  return (
    <AppLayout>
      <div className="space-y-6">
        {/* Breadcrumb */}
        <div className="flex items-center gap-2 text-sm text-muted-foreground">
          <span>AI Tools</span>
          <ChevronRight className="h-4 w-4" />
          <span className="text-foreground font-medium">AI Test Generation</span>
        </div>

        {/* Header */}
        <div>
          <h1 className="text-3xl font-bold text-foreground flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary">
              <Sparkles className="h-6 w-6 text-primary-foreground" />
            </div>
            AI Test Generation
          </h1>
          <p className="text-muted-foreground mt-2">
            Generate comprehensive test cases from feature descriptions, user stories, or requirements
          </p>
        </div>

        <div className="grid gap-6 lg:grid-cols-2">
          {/* Input Section */}
          <Card className="border-border">
            <CardHeader>
              <CardTitle className="text-foreground">Input</CardTitle>
              <CardDescription>
                Provide a feature description or user story to generate test cases
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid gap-2">
                <Label>Target Project</Label>
                <Select value={selectedProjectId} onValueChange={setSelectedProjectId}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select a project to save tests to" />
                  </SelectTrigger>
                  <SelectContent>
                    {projects?.map((p) => (
                      <SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="grid gap-2">
                <Label>Input Type</Label>
                <Select value={inputType} onValueChange={setInputType}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="description">Feature Description</SelectItem>
                    <SelectItem value="user_story">User Story</SelectItem>
                    <SelectItem value="requirements">Requirements Document</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="grid gap-2">
                <Label>
                  {inputType === "description"
                    ? "Feature Description"
                    : inputType === "user_story"
                    ? "User Story"
                    : "Requirements"}
                </Label>
                <Textarea
                  placeholder={
                    inputType === "description"
                      ? "Describe the feature you want to test...\n\nExample: User authentication with login, logout, and password reset functionality"
                      : inputType === "user_story"
                      ? "Enter your user story...\n\nExample: As a user, I want to log in with my credentials so that I can access my account securely"
                      : "Paste or describe the requirements..."
                  }
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  className="min-h-[200px] resize-none"
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="grid gap-2">
                  <Label>Default Priority</Label>
                  <Select value={defaultPriority} onValueChange={setDefaultPriority}>
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="critical">Critical</SelectItem>
                      <SelectItem value="high">High</SelectItem>
                      <SelectItem value="medium">Medium</SelectItem>
                      <SelectItem value="low">Low</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="grid gap-2">
                  <Label>Test Type</Label>
                  <Select value={testType} onValueChange={setTestType}>
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="functional">Functional</SelectItem>
                      <SelectItem value="security">Security</SelectItem>
                      <SelectItem value="performance">Performance</SelectItem>
                      <SelectItem value="integration">Integration</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <Button
                className="w-full"
                size="lg"
                onClick={handleGenerate}
                disabled={isGenerating}
              >
                {isGenerating ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Generating with AI...
                  </>
                ) : (
                  <>
                    <Wand2 className="mr-2 h-4 w-4" />
                    Generate Test Cases
                  </>
                )}
              </Button>
            </CardContent>
          </Card>

          {/* Generated Tests Section */}
          <Card className="border-border">
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle className="text-foreground">Generated Test Cases</CardTitle>
                  <CardDescription>
                    Review and save AI-generated test cases
                  </CardDescription>
                </div>
                {generatedTests.length > 0 && (
                  <Button onClick={handleSaveSelected} disabled={isSaving || !selectedProjectId}>
                    {isSaving ? (
                      <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> Saving...</>
                    ) : (
                      <><Save className="mr-2 h-4 w-4" /> Save Selected</>
                    )}
                  </Button>
                )}
              </div>
            </CardHeader>
            <CardContent>
              {generatedTests.length === 0 ? (
                <div className="flex flex-col items-center justify-center py-12 text-center">
                  <div className="flex h-16 w-16 items-center justify-center rounded-full bg-accent mb-4">
                    <FileText className="h-8 w-8 text-accent-foreground" />
                  </div>
                  <h3 className="text-lg font-medium text-foreground mb-2">
                    No test cases yet
                  </h3>
                  <p className="text-sm text-muted-foreground max-w-sm">
                    Enter a feature description and click "Generate Test Cases" to
                    see AI-generated test cases here.
                  </p>
                </div>
              ) : (
                <div className="space-y-4 max-h-[600px] overflow-y-auto pr-2">
                  {generatedTests.map((test) => (
                    <div
                      key={test.id}
                      className={cn(
                        "rounded-lg border border-border p-4 transition-all",
                        test.selected && "border-primary bg-accent/50"
                      )}
                    >
                      <div className="flex items-start gap-3">
                        <Checkbox
                          checked={test.selected}
                          onCheckedChange={() => toggleTestSelection(test.id)}
                          className="mt-1"
                        />
                        <div className="flex-1 space-y-2">
                          <div className="flex items-start justify-between gap-2">
                            <h4 className="font-medium text-foreground">{test.name}</h4>
                            <div className="flex items-center gap-2">
                              <Badge
                                className={cn(
                                  "capitalize text-xs",
                                  priorityColors[test.priority] || priorityColors.medium
                                )}
                              >
                                {test.priority}
                              </Badge>
                              <Badge variant="outline" className="text-xs">
                                {test.type}
                              </Badge>
                            </div>
                          </div>
                          <p className="text-sm text-muted-foreground">
                            {test.description}
                          </p>
                          <div className="space-y-1">
                            <p className="text-xs font-medium text-muted-foreground">
                              Steps ({test.steps.length}):
                            </p>
                            <div className="space-y-1 pl-2 border-l-2 border-border">
                              {test.steps.slice(0, 3).map((step, idx) => (
                                <p key={idx} className="text-xs text-muted-foreground">
                                  {idx + 1}. {step.action}
                                </p>
                              ))}
                              {test.steps.length > 3 && (
                                <p className="text-xs text-primary">
                                  +{test.steps.length - 3} more steps
                                </p>
                              )}
                            </div>
                          </div>
                          <div className="flex items-center gap-2 pt-2">
                            <Button
                              variant="ghost"
                              size="sm"
                              className="text-destructive hover:text-destructive"
                              onClick={() => removeTest(test.id)}
                            >
                              <Trash2 className="mr-1 h-3 w-3" />
                              Remove
                            </Button>
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      </div>
    </AppLayout>
  );
}
